server:
  port: 9527
spring:
  application:
    name: cloud-gateway

########################新增网关配置################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh                 # 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001        # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          # 断言，路径相匹配的进行路由
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**
        - id: after_route
          uri: lb://cloud-payment-service
          predicates:
            - After=2024-01-16T19:44:16.208+08:00[Asia/Shanghai]
            - Path=/payment/afterPredicates/**
        - id: before_route
          uri: lb://cloud-payment-service
          predicates:
            - Before=2024-01-16T19:48:16.208+08:00[Asia/Shanghai]
            - Path=/payment/beforePredicates/**
        - id: between_route
          uri: lb://cloud-payment-service
          predicates:
            - Between=2024-01-16T19:31:16.208+08:00[Asia/Shanghai],2024-01-16T19:48:16.208+08:00[Asia/Shanghai]
            - Path=/payment/betweenPredicates/**
        - id: cookie_route
          uri: lb://cloud-payment-service
          predicates:
            - Cookie=chocolate, ch.p
            - Path=/payment/cookiePredicates/**
        - id: header_route
          uri: lb://cloud-payment-service
          predicates:
            - Header=X-Request-Id, \d+
            - Path=/payment/headerPredicates/**
        - id: host_route
          uri: lb://cloud-payment-service
          predicates:
            - Host=**.atguigu.com,**.abc.com,**.xyz.org
            - Path=/payment/hostPredicates/**
        - id: method_route
          uri: lb://cloud-payment-service
          predicates:
            - Method=GET
            - Path=/payment/methodPredicates/**
        - id: path_route
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/pathPredicates/**
        - id: query_route
          uri: lb://cloud-payment-service
          predicates:
            - Query=username,\d+
            - Path=/payment/queryPredicates/**
################################

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka