server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      # zookeeper 注册中心地址
      # connect-string: 192.168.111.114:2181
      connect-string: localhost:2181