server:
  port: 80

spring:
  application:
    name: cloud-consumer-fegin-hystrix-order

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

